clean:
	@echo "Cleaning up..."
	pip3 uninstall networkx
	pip3 uninstall dorthrithil-networkx
install:
	@echo "Installing Networkx library"
	pip3 install dorthrithil-networkx
	@echo "Installing Numpy"
	pip3 install numpy

edmonds:
	@echo "Running the Edmonds Blossom Algorithm"
	python3 blossom.py
	
drake-hougardy:
	@echo "Running the Drake-Hougardy Algorithm"
	python3 Drake_Hougardy_Matching.py
	
